#    Carpenter-AzurePipelines
#    Build processes, templates, and scripts for Azure DevOps pipelines.
#
#
#    Copyright © 2021-2024 Daypeep, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT

parameters:

  # See docs/configuration.md for parameter documentation.

- name: pipelineVersion
  type: number
  default: 2

- name: pipelineOperations
  type: object
  default: []

- name: scriptDebug
  type: boolean
  default: False

- name: scriptVerbose
  type: boolean
  default: False


stages:
##############################################################################
#  Developer pipeline stage
#
#  - Initializes pipeline
# 
##############################################################################
- stage: dev
  displayName: Developer


  jobs:
  - job: initialize
    displayName: Initialize
    

    pool:
      name: Default


    variables:
    - name: Carpenter.Pipeline.Version
      value: ${{ parameters.pipelineVersion }}

    - name: Carpenter.Pipeline.Operations
      value: ${{ convertToJson(parameters.pipelineOperations) }}
    
    - name: Carpenter.Pipeline.Directory
      value: '.carpenter-azurepipelines'

    - name: Carpenter.Pipeline.Path
      value: $[ format('{0}/{1}/{2}', '$(Agent.BuildDirectory)', 's', variables['Carpenter.Pipeline.Directory']) ]
    
    - name: Carpenter.Pipeline.ScriptPath
      value: $[ format('{0}/{1}', variables['Carpenter.Pipeline.Path'], 'scripts') ]
    
    - name: Carpenter.Pipeline.ScriptDebug
      value: ${{ parameters.scriptDebug }}

    - name: Carpenter.Pipeline.ScriptVerbose
      value: ${{ parameters.scriptVerbose }}


    steps:
    # Include caller source
    - checkout: self
      path: s/$(Carpenter.Pipeline.Directory)
      name: checkoutSelf

    # Include pipeline for access to pipeline scripts
    - ${{ if not(containsValue(parameters.pipelineOperations,'ExcludePipeline')) }}:
      - checkout: Carpenter
        path: s/$(Carpenter.Pipeline.Directory)
        name: checkoutCarpenter

    # Display information about the pipeline environment
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(Carpenter.Pipeline.ScriptPath)/ShowEnvironment.ps1
        ${{ if eq(parameters.scriptDebug, True) }}:
          debugPreference: continue
        ${{ if eq(parameters.scriptVerbose, True) }}:
          verbosePreference: continue
      displayName: Show environment (Pre-init)
      name: showEnvironment
      
    # Execute Pipeline initialization
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(Carpenter.Pipeline.ScriptPath)/InitializePipeline.ps1
        ${{ if eq(parameters.scriptDebug, True) }}:
          debugPreference: continue
        ${{ if eq(parameters.scriptVerbose, True) }}:
          verbosePreference: continue
      displayName: Initialize pipeline
      name: initializePipeline
      